(cl:defpackage gpd_ros-srv
  (:use )
  (:export
   "GRASP2DPREDICTION"
   "<GRASP2DPREDICTION-REQUEST>"
   "GRASP2DPREDICTION-REQUEST"
   "<GRASP2DPREDICTION-RESPONSE>"
   "GRASP2DPREDICTION-RESPONSE"
   "GRASPPREDICTION"
   "<GRASPPREDICTION-REQUEST>"
   "GRASPPREDICTION-REQUEST"
   "<GRASPPREDICTION-RESPONSE>"
   "GRASPPREDICTION-RESPONSE"
   "DETECT_GRASPS"
   "<DETECT_GRASPS-REQUEST>"
   "DETECT_GRASPS-REQUEST"
   "<DETECT_GRASPS-RESPONSE>"
   "DETECT_GRASPS-RESPONSE"
  ))

