(cl:defpackage ros_deep_grasp-srv
  (:use )
  (:export
   "GRASP2DPREDICTION"
   "<GRASP2DPREDICTION-REQUEST>"
   "GRASP2DPREDICTION-REQUEST"
   "<GRASP2DPREDICTION-RESPONSE>"
   "GRASP2DPREDICTION-RESPONSE"
   "GRASPPREDICTION"
   "<GRASPPREDICTION-REQUEST>"
   "GRASPPREDICTION-REQUEST"
   "<GRASPPREDICTION-RESPONSE>"
   "GRASPPREDICTION-RESPONSE"
  ))

