set(gazebo_grasp_plugin_ros_MESSAGE_FILES "/root/grasping_benchmarking/benchmarking_ws/src/benchmarking_vision_based_grasping/grasp_plugin/gazebo-pkgs/gazebo_grasp_plugin_ros/msg/GazeboGraspEvent.msg")
set(gazebo_grasp_plugin_ros_SERVICE_FILES "")
